name: Semantic PR Check

on:
  pull_request_target:
    types: [opened, synchronize, edited]

permissions:
  pull-requests: read

jobs:
  pr-title-check:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title follows conventional commits
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            perf
            docs
            test
            refactor
            style
            build
            ci
            chore
            revert
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            must start with a lowercase letter.

            Please check: https://github.com/amplitude/experiment-flutter-client/blob/main/CONTRIBUTING.md#pr-commit-title-conventions
          validateSingleCommit: true
